### ISSUE TITLE
Pagination URL detection

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1716]
Nginx: 1.6.0
PHP-FPM: 5.5.12

I have created a paginator 

```
$pagination = Pagination::forge('default', array(
    'uri_segment' => 2,
    'total_items' => 1000,
    'per_page' => 10
));
```

on this page:

https://example.com/results/?filter=1&date=2014-06-19

but the paginator will create this links (he will add the complete query string)

https://example.com/results/2?results%2F=&filter=1&date=2014-06-19

I think the will be at 

```
Input::get()
```

because on https://example.com/controller/method.json?test=123

it will return

```
array(2) { ["controller/method_json"]=> string(0) "" ["test"]=> string(3) "123" }
```

**Comment by WanWizard** [comment]
Input::get() just access $_GET, so I don't think that is the problem. 

The problem is probably in Input::uri(). You're on 1.8/develop? Can you check at https://github.com/fuel/core/blob/1.8/develop/classes/input.php#L143 what is in $uri, and post that here? I don't have an nginx setup to test atm.

**Comment by dercoder** [comment]
I found the problem

Problem:

```
location / {
    if (!-e $request_filename) {
        rewrite  ^/(.*)$  /index.php?$1  last;
        break;
    }
}
```

Fixed:

```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```

So there is no path included in QUERY_STRING

I have used ZF Nginx configuration:
http://wiki.nginx.org/Zend_Framework

Maybe you can put this information to your online documentation

**Comment by WanWizard** [comment]
Still that doesn't fix the detection problem in input, you just worked around it. What was the EXACT content of $_SERVER['QUERY_STRING'] before you worked around it? I'd rather make sure Input can handle that format.

**Comment by dercoder** [comment]
Request: http://www.example.com/welcome/index/?test=123
Please check the **QUERY_STRING**

###### Before (INCORRECT)

```
print_r($_SERVER);
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [FCGI_ROLE] => RESPONDER
    [SCRIPT_FILENAME] => /var/www/test/public/index.php
    [FUEL_ENV] => development
    [QUERY_STRING] => welcome/index/?test=123
    [REQUEST_METHOD] => GET
    [CONTENT_TYPE] =>
    [CONTENT_LENGTH] =>
    [SCRIPT_NAME] => /index.php
    [REQUEST_URI] => /welcome/index/?test=123
    [DOCUMENT_URI] => /index.php
    [DOCUMENT_ROOT] => /var/www/test/public
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_SOFTWARE] => nginx/1.6.0
    [SERVER_PORT] => 8012
    [REDIRECT_STATUS] => 200
    [HTTP_CONNECTION] => keep-alive
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1403351695.1036
    [REQUEST_TIME] => 1403351695
)
```

```
var_dump($_GET);
array(2) {
    ["welcome/index/"]=> string(0) ""
    ["test"]=> string(3) "123"
}
```

###### After (CORRECT)

```
print_r($_SERVER);
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [FCGI_ROLE] => RESPONDER
    [SCRIPT_FILENAME] => /var/www/test/public/index.php
    [FUEL_ENV] => development
    [QUERY_STRING] => test=123
    [REQUEST_METHOD] => GET
    [CONTENT_TYPE] =>
    [CONTENT_LENGTH] =>
    [SCRIPT_NAME] => /index.php
    [REQUEST_URI] => /welcome/index/?test=123
    [DOCUMENT_URI] => /index.php
    [DOCUMENT_ROOT] => /var/www/test/public
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_SOFTWARE] => nginx/1.6.0
    [SERVER_PORT] => 8011
    [REDIRECT_STATUS] => 200
    [HTTP_CONNECTION] => keep-alive
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1403351588.4428
    [REQUEST_TIME] => 1403351588
)
```

```
var_dump($_GET);
array(1) {
    ["test"]=> string(3) "123"
}
```

**Comment by WanWizard** [comment]
Weird, I have a feeling the problem isn't in Fuel at all, but it is at tthe PHP level? Even if I use your "incorrect" input in the index.php to fake your request, I get a result that is ok. 

What does $_GET contain in your incorrect situation when you dump it in your index.php, before Fuel starts ?

**Comment by dercoder** [comment]
This is just a Nginx configuration issue.

I have added 

```
var_dump($_SERVER['QUERY_STRING']);
var_dump($_GET);
```

directly into /public/index.php

**Test 1: http://www.example.com/index.php/welcome/index/?test=123**

Result with old nginx config:

```
string(8) "test=123"
array(1) {
    ["test"]=> string(3) "123"
}
```

Result with new nginx config:

```
string(8) "test=123"
array(1) {
    ["test"]=> string(3) "123"
}
```

So both results are correct using this url format

**Test 2: http://www.example.com/welcome/index/?test=123**

Result with old nginx config:

```
string(23) "welcome/index/&test=123"
array(2) {
    ["welcome/index/"]=> string(0) ""
    ["test"]=> string(3) "123"
}

```

Result with new nginx config:

```
string(8) "test=123"
array(1) {
    ["test"]=> string(3) "123"
}
```

**So only the new nginx configuration will be correct**

This is my new nginx configuration:

```
root  /var/www/test/public;
index  index.html index.htm index.php;

location / {
       try_files $uri $uri/ /index.php$is_args$args;
}

location ~ \.php(.*)$ {
       fastcgi_pass unix:/var/run/php5-fpm.sock;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_param FUEL_ENV "development";
       include /etc/nginx/fastcgi_params;
}
```

If you dont want "/index.php/controller/method/" support you can replace

```
location ~ \.php(.*)$
```

with

```
location ~ \.php$
```

I have already testet this configuration on all development projects. 
Thats why i think you should add this configuration (http://wiki.nginx.org/Zend_Framework)
in your docs

**Comment by WanWizard** [comment]
Well, if PHP parses it correctly, but in your controller it's wrong, then Fuel most have changed it. Problem is I can't reproduce it with the $_SERVER array you posted. 

Which Fuel version are you on? I have a feeling I'm chasing a ghost here. I triple checked the entire core, there is no code that alters $_GET, except for in Input:uri(), and then only if the rewrite is so broken that there is no QUERY_STRING at all...

**Comment by dercoder** [comment]
PHP and Fuel parses them correctly. Only Nginx submits the wrong QUERY_STRING with this wrong Nginx configuration. The problem is that there are many ways to configurate Nginx + PHP-FPM, but not all of them will work correctly

In this case 

```
location / {
    if (!-e $request_filename) {
        rewrite  ^/(.*)$  /index.php?$1  last;
        break;
    }
}
```

the nginx server will send the complete URI as QUERY_STRING to PHP and thats not correct. The rewrite rule was not correct !!!

So FuelPHP and PHP itself are working fine. But i think there is only one right way to configure Nginx with PHP-FPM to prevent this issue. So thats why i think you should add this Nginx configuration here:
http://fuelphp.com/docs/installation/instructions.html#/install_inside_root2

**Comment by WanWizard** [comment]
You're missing the point. 

If when index.php is loaded $_GET is correct (with all nginx configs you used), and it is no longer when the controller is loaded, the only conclusion is that $_GET was modified in between. Since there is only one line of code in the entire framework that alters $_GET, and it only does that if QUERY_STRING is empty, the question what changes your GET data is still not answered.

Are you now saying $_GET is wrongly interpreted by PHP too, when the nginx rewrite is wrong?

**Comment by dercoder** [comment]
Maybe this Example will clearify it

Request: http://www.example.com/welcome/index/?test=123
index.php file:

```
<?php
var_dump($_GET):
?>
```

This Nginx config

```
location / {
    if (!-e $request_filename) {
        rewrite  ^/(.*)$  /index.php?$1  last;
        break;
    }
}
```

will return

```
array(2) {
    ["welcome/index/"]=> string(0) ""
    ["test"]=> string(3) "123"
}
```

This Nginx config

```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```

will return

```
array(1) {
    ["test"]=> string(3) "123"
}
```

So the wrong Nginx config will add the complete query to $_GET instead only the variables after ?

This is how PHP will see the request with this wrong nginx config (rewrite  ^/(.*)$  /index.php?$1  last;)
https://www.example.com/index.php?index.php&test=123

```
string(18) "index.php&test=123"
array(2) {
  ["index_php"]=> string(0) ""
  ["test"]=> string(3) "123"
}
```

instead of
https://www.example.com/index.php?test=123

```
string(8) "test=123"
array(1) {
  ["test"]=> string(3) "123"
}
```

So PHP gets just wrong parameters to interpret. So everything is fine with FuelPHP and PHP

**Comment by WanWizard** [comment]
So, so you confirm that it causes PHP itself can get the wrong data. Cool. Let's close this then.

**Comment by dercoder** [comment]
Yes correct. You can close it but it would be nice to add the correct Nginx config into your docs like you do for Apache
