### ISSUE TITLE
Upload::is_valid() returns true when no files uploaded

### ISSUE THREAD

**Issue by andrewwheal** [fuel/core#413]
The documentation says that the Upload::is_valid() method should be "used to check if there are any uploaded files present that have been validated".

However, if no files are uploaded Upload::is_valid() still returns true.

**Comment by WanWizard** [comment]
What version of Fuel are you using? This has been fixed a week or two ago...

**Comment by andrewwheal** [comment]
Oh, sorry... just updated to latest develop branch and will test again once I have a working site again

**Comment by andrewwheal** [comment]
After updating my core to the latest 1.1/develop branch this is still an issue.

Submitting a form with a file field gives:

var_dump(\Upload::get_files());
// array
//   empty

var_dump(\Upload::is_valid());
// boolean true

**Comment by WanWizard** [comment]
Fixed, is_valid() now returns true only if at least one validated file is present.
