### ISSUE TITLE
General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#919]
> Error - SQLSTATE[HY000]: General error: 2006 MySQL server has gone away with query: [...] in COREPATH/classes/database/pdo/connection.php on line 137

Seemingly at random, I suspect when the web server is under load, I receive these errors. When it does happen, it usually happens when running a task that will run for a long time. This issue doesn't happen all of the time.

One task in particular runs for several hours, it will do several queries initially to get the data we currently have, then will connect to an external API to download all the data, then PHP is used to merge this so we have the latest data, then finally we insert the new data. This action is performed hundreds of times as the API "paginates" the data we receive.

So during the time PHP is requesting data from the API, or processing the data, the MySQL connection hasn't be used for a relatively long time. So when the application then wants to run a query, it gets this error from the Client because the Server has (rightly) killed the connection as it assumes it is idle or timed out.

When this happens, it would be good if Fuel reconnected to the database; Ideally this functionality should be added to the layer between the application and the database once, rather than spread around the entire application in multiple places.

I will attempt to recreate the issue and hopefully submit some code that does this.

**Comment by huglester** [comment]
Hello,

I remember having similar issue on one of my older projects. The problem was they delay between mysql connections - so mysql just timed out the connection - and you have this error.

The solution was just in a meantime do db reconnect.

Hope that helps :)

**Comment by lukearmstrong** [comment]
Looks like the reason it is happening for me is because of this setting on our mysql server.

http://dev.mysql.com/doc/refman/5.0/en/server-system-variables.html#sysvar_wait_timeout

Our development server has the default, 28800 seconds (8 hours).
But our live server is set to 60 seconds.

I should be able to come up with a fix so that it attempts to reconnect if the exception thrown is `General error: 2006 MySQL server has gone away`.

Not sure of the best way of doing it yet, but I will have a go.

In my case I am using PDO, so from the looks of it, I should attempt to reconnect in `Fuel\Core\Database_PDO_Connection::query()`, specifically the catch block starting at Line 128: `fuel/core/classes/database/pdo/connection.php`

**Comment by lukearmstrong** [comment]
Here's a simple task I made to reproduce it.

``` php
<?php

namespace Fuel\Tasks;

class Wait_Timeout
{
    public static function run()
    {
        \DB::query("SET SESSION wait_timeout = 5")->execute();

        $one = \DB::query("SELECT 1")->execute();
        print_r($one);

        sleep(10);

        $two = \DB::query("SELECT 2")->execute();
        print_r($two);
    }
}
```

**Comment by huglester** [comment]
Yeah it must be smth to do with timeout.
Maybe there should be an option to allow 'reconnecting' or smth, if the time between last and previous queries are X secnds/minutes, etc.

WHat I get is: 
http://d.pr/i/1CZy

But the error is different beacause of driver I think.
ANd yes, if I remove sleep() - all works

**Comment by lukearmstrong** [comment]
This only seems to be a problem for one task that takes a long time to run, so my temporary fix at the moment is just to set the wait_timeout back to the default at the beginning of the task. `SET SESSION` only changes it for this connection, so it won't be done for all connections.

``` php
<?php

\DB::query("SET SESSION wait_timeout = 28800")->execute();
```

The reason I call it a temporary fix is because there are other problems that cause a database connection to be unusable, so in any case the Database Class (or their extensions) should always attempt to reconnect on failure. I can't think of why you would want to make this a configurable option though.

Who wants an exception to be thrown that terminates the application?

**Comment by WanWizard** [comment]
I've been thinking about this for a few days now.

It's my opinion that your database should not disconnect within 10 seconds, that's a sign of poor configuration, by default PHP scripts can run for 30 seconds. So it should be solved there, not worked around in the framework code. 

And if you have a long-running task, you normally would change the PHP script timeout, so why not the DB session timeout?

**Comment by lukearmstrong** [comment]
Our dedicated db server is set to 60 seconds because there were problems with sites running in other languages/frameworks/etc on other servers. I believe this setting was changed because ASP creates persistent connections, but then is unable to reuse them, which eventually causes a max connections error.

I believe our PHP timeout is the default, and is not changed by this task.

Regarding my specific issue, you are right, it's a configuration issue which I have sidestepped by modifying the configuration for this task.

But it highlights a broader issue, where the connection is unusable. The DB class attempts to use this connection without either checking it is still active (not sure how you would do this), or without attempting to reconnect when there is a problem. So when there is a problem, the DB class throws an exception, which is caught, but then throws another one, which is not caught - causing the script to terminate, when it may well have continued running if it reconnected to the DB.

Putting everything in the app that accesses the DB in a try/catch is not really feasible, and I believe a more comprehensive solution may be to attempt to reconnect if there is an error in the DB classes.

**Comment by huglester** [comment]
While in PHP, you can't change timeout limit from framework or somehow 'fix' it
in mysql - we can - with reconnect.

so maybe it would be good addition? I myself didn't meet this specific problem ever yet, but who knows ..:)

**Comment by tarnfeld** [comment]
Awesome this is fixed, just to interject anyway - I think its bad this never worked like that, I was just investigating if this worked this way because one of the biggest problem I have is slow clients (i.e. making a call to an api between queries) are hogging mysql connections...

Anyway, fab this is fixed!

**Comment by WanWizard** [comment]
I'm still not in favour of this. If your environment is configured properly your database should not disconnect faster then your PHP execution timeout. But appearently I'm alone in this...

**Comment by lukearmstrong** [comment]
@WanWizard I agree, but there could be other issues that cause a connection to be dropped. Thanks for the fix.

**Comment by tarnfeld** [comment]
@WanWizard Definitely with the timeout, but for me if a client connects to the db and proceeds to process for 10 seconds, that connection is wasted and could be used for another client... can definitely cause issues when trying to push as much through mysql as possible.

**Comment by kingpinwebdesigns** [comment]
Hey guys, I never really add anything to the forums, but I have been following Fuel for quite some time... I just got the same issue here.

It seems the PDO connection is lost, and it IS throwing the error, which means the 2 attempts at reconnecting aren't enough??? 

Super weird, it had never came up during development and as soon as it got put up on the live server, running the same exact tests with OIL CONSOLE the connection is lost.  Works just fine, then after like a few seconds of no db activity in the console, it shuts down... 

I am trying to see if mysql 5.1 is the problem, but anyway, any thoughts are appreciated!

**Comment by WanWizard** [comment]
The fix doesn't do a second attempt, it will try to reconnect every time a query fails. If will only bail out with the exception if that reconnect fails.

So I would check out your MySQL config, to find out why it is dropping connections so fast, and why a reconnect (which is basically not a reconnect, but creating a new PDO connection object) fails.

**Comment by kingpinwebdesigns** [comment]
The same thing has happened while using the mysql command line... but it does reconnect, it shows the same error, but then reconnects, and grabs the data... so there is a .02 second delay before the result gets populated...  

I am being told:

This error message is a common message seen if there are too many long-running queries on the server, or if your VPS has hit it's connection resource limits. I currently see 1,813 fail counts/alerts for your "numothersock" virtual resource - this is one of the main resources MySQL uses.

About the second reconnect, I noticed in the connection class function connect() that it only checks if $this->_connection is !== false, but i am not seeing anything checking for if the connection had been lost.   Would it make sense to to call disconnect() first in the catch?

try
{
    try
    {
        $result = $this->_connection->query($sql);
    }
    catch (\Exception $e)
    {
        // do a reconnect first and try again, before giving up
        $this->disconnect();
        $this->connect();
        $result = $this->_connection->query($sql);
    }
}
catch (\Exception $e)
{
    if (isset($benchmark))
    {
        // This benchmark is worthless
        \Profiler::delete($benchmark);
    }

```
// Convert the exception in a database exception
throw new \Database_Exception($e->getMessage().' with query: "'.$sql.'"');
```

}

**Comment by WanWizard** [comment]
Connecting is a one-time operation, in normal circumstances the connection should live for the duration of the request.

When you fire a new query, and the connection is lost, it will generate an exception. The driver will then attempt a reconnect, and run the query again. If that fails a second time, the driver bails out with the exception.

Disconnecting is a very bad idea, that means introducing a .02 second delay before each and every query, and you're driving your database server nuts with constant disconnects and reconnects.

Imho configuring your database server with an extremely short connection timeout is a plain stupid thing to do. It will create extra load on your database server, constant reconnects in your app adding processing time and load ,and you don't gain anything.

The MySQL commandline client has built-in logic for automatic reconnects, that's why you only notice the slight delay. PHP's PDO wrapper doesn't, so you have to work around it, which we tried.

I found an alternative solution made by Digg, I can see if I can implement that.

**Comment by kingpinwebdesigns** [comment]
I will also continue to look as well and post back… there are just so many damn things to worry about!  What do you recommend on the connection time-outs?  Also, do you see this as a problem while running a long cron-job that makes a ton of api requests in between database inserts / selects, or is this something that I run into only while using OIL CONSOLE?

So even though the disconnect() / connect() would only happen inside the second try, you still see that as a bad thing?  

Thanks for everything man, really.

**Comment by WanWizard** [comment]
@kingpinwebdesigns see if this improves things...

**Comment by kingpinwebdesigns** [comment]
Thanks Harro, I will test this out once the hosting provider removes my ip address from a blacklist. ;)  have no idea why that happened… too many ssh connections maybe.

**Comment by kingpinwebdesigns** [comment]
Hey Harro, 

Sorry it took forever to get back to you on this one, but I think there is a huge no-no on this latest fix… as it is, it inserts 3 records at once!  I changed it to this:

```
    do
    {
        try
        {
            $result = $this->_connection->query($sql);
            $attempts = 3;
        }
        catch (\Exception $e)
        {
            if (strpos($e->getMessage(), '2006 MySQL') !== false)
            {
                $this->connect();
            }
            else
            {
                if (isset($benchmark))
                {
                    // This benchmark is worthless
                    \Profiler::delete($benchmark);
                }

                // Convert the exception in a database exception
                throw new \Database_Exception($e->getMessage().' with query: "'.$sql.'"');
            }
        }
    }
    while ($attempts++ < 3);
```

Ryan

**Comment by WanWizard** [comment]
It was missing a break statement after the query() call. I've fixed it.
